title: "Python Pro"
description: "Expertise Python & Kivy à l'Université Kongo"
remote_theme: jekyll/minima

# Les plugins doivent être au bord gauche
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuration du style
minima:
  skin: dark
  social_links:
    - { platform: github, user: Exauce01159 }
    - { platform: linkedin, user: exauce-kisiabongo }
    - { platform: whatsapp, user: 243842317817 }
    
